stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/twcs.csv
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv